### PR TITLE
Adds diacritical marks to pinyin

### PR DESCRIPTION
**Pull request by pmitros**
This improves the pinyin output of the library by adding diacriticals. Diacriticals are essential especially for Western speakers trying to read pinyin. It maintains the ability to output plain ASCII text by supporting either stripped pinyin or tone numbers.

### CODE REVIEW

**Comment by pmitros** [comment]
@lxyu Would you mind having a look? This makes the pinyin output much nicer. It makes it possible for Westerners like myself to be able to read the text output by adding tone marks. It does change the output, so it may break test cases in downstream code, but I'd rather have sensible output in downstream systems where possible.

**Comment by pmitros** [comment]
(Rebases are for compatibility with Python 3.2, which is in your CI, but not on my local system)

**Comment by lxyu** [comment]
Thanks very much, I think it's very cool and useful!

**Comment by lxyu** [comment]
I'll submit a pypi release a few days later when this new year holiday ends.

**Comment by lxyu** [comment]
Released as 0.3

**Pull request merged**
